z=[
{
'name':'首页',
'url':'//www.bilibili.com/index.html',
'route':'/',
'tid':'',
'locid':23,
'sub':[
]
},
{
'name':'动画',
'route':'douga',
'tid':1,
'locid':52,
'url':'//www.bilibili.com/video/douga.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2507,
'leftId':2452,
'rightId':2453
},
'sub':[
{
'name':'MAD·AMV',
'route':'mad',
'tid':24,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':151
},
'desc':'具有一定制作程度的动画或静画的二次创作视频',
'url':'//www.bilibili.com/video/douga-mad-1.html'
},
{
'name':'MMD·3D',
'route':'mmd',
'tid':25,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':152
},
'desc':'使用MMD（MikuMikuDance）和其他3D建模类软件制作的视频',
'url':'//www.bilibili.com/video/douga-mmd-1.html'
},
{
'name':'短片·手书·配音',
'route':'voice',
'tid':47,
'ps':15,
'rps':10,
'desc':'追求创新并具有强烈特色的短片、手书（绘）及ACG相关配音',
'url':'//www.bilibili.com/video/douga-voice-1.html'
},
{
'name':'综合',
'route':'other',
'tid':27,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':153
},
'desc':'以动画及动画相关内容为素材，包括但不仅限于音频替换、杂谈、排行榜等内容',
'url':'//www.bilibili.com/video/douga-else-1.html'
}
]
},
{
'name':'番剧',
'route':'anime',
'tid':13,
'url':'//www.bilibili.com/anime/',
'takeOvered':0,
'count':'',
'sub':[
{
'name':'连载动画',
'tid':33,
'route':'serial',
'desc':'当季连载的动画番剧',
'url':'//www.bilibili.com/video/bangumi-two-1.html'
},
{
'name':'完结动画',
'tid':32,
'route':'finish',
'desc':'已完结的动画番剧合集',
'url':'//www.bilibili.com/video/part-twoelement-1.html'
},
{
'name':'资讯',
'tid':51,
'route':'information',
'desc':'动画番剧相关资讯视频',
'url':'//www.bilibili.com/video/douga-else-information-1.html'
},
{
'name':'官方延伸',
'tid':152,
'route':'offical',
'desc':'动画番剧为主题的宣传节目、采访视频，及声优相关视频',
'url':'//www.bilibili.com/video/bagumi_offical_1.html'
},
{
'name':'新番时间表',
'url':'//www.bilibili.com/anime/timeline/',
'desc':''
},
{
'name':'番剧索引',
'url':'//www.bilibili.com/anime/index/',
'desc':''
}
]
},
{
'name':'国创',
'tid':167,
'route':'guochuang',
'url':'//www.bilibili.com/guochuang/',
'takeOvered':0,
'count':'',
'sub':[
{
'name':'国产动画',
'tid':153,
'route':'chinese',
'desc':'我国出品的PGC动画',
'url':'//www.bilibili.com/video/bangumi_chinese_1.html'
},
{
'name':'国产原创相关',
'tid':168,
'route':'original',
'desc':'',
'url':'//www.bilibili.com/video/guochuang-fanvid-1.html'
},
{
'name':'布袋戏',
'tid':169,
'route':'puppetry',
'desc':'',
'url':'//www.bilibili.com/video/glove-puppetry-1.html'
},
{
'name':'动态漫·广播剧',
'tid':195,
'route':'motioncomic',
'desc':'',
'url':''
},
{
'name':'资讯',
'tid':170,
'route':'information',
'desc':'',
'url':'//www.bilibili.com/video/guochuang-offical-1.html'
},
{
'name':'新番时间表',
'url':'//www.bilibili.com/guochuang/timeline/',
'desc':''
},
{
'name':'国产动画索引',
'url':'//www.bilibili.com/guochuang/index/',
'desc':''
}
]
},
{
'name':'音乐',
'route':'music',
'tid':3,
'locid':58,
'url':'//www.bilibili.com/video/music.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':0,
'customComponent':{
'name':'Energy',
'titleId':2511,
'leftId':2462,
'rightId':3131,
'rightType':'slide'
},
'sub':[
{
'name':'原创音乐',
'route':'original',
'tid':28,
'ps':15,
'rps':10,
'viewHotTag':0,
'ad':{
'active':0,
'dataLocId':243
},
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'个人或团队制作以音乐为主要原创因素的歌曲或纯音乐',
'url':'//www.bilibili.com/video/music-original-1.html'
},
{
'name':'翻唱',
'route':'cover',
'tid':31,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':245
},
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'一切非官方的人声再演绎歌曲作品',
'url':'//www.bilibili.com/video/music-Cover-1.html'
},
{
'name':'VOCALOID·UTAU',
'route':'vocaloid',
'tid':30,
'ps':15,
'rps':10,
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'以雅马哈Vocaloid和UTAU引擎为基础，包含其他调教引擎，运用各类音源进行的歌曲创作内容',
'url':'//www.bilibili.com/video/music-vocaloid-1.html'
},
{
'name':'电音',
'route':'electronic',
'tid':194,
'ps':15,
'rps':10,
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'以电子合成器、音乐软体等产生的电子声响制作的音乐',
'url':'#'
},
{
'name':'演奏',
'route':'perform',
'tid':59,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':247
},
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'传统或非传统乐器及器材的演奏作品',
'url':'//www.bilibili.com/video/music-perform-1.html'
},
{
'name':'MV',
'route':'mv',
'tid':193,
'ps':15,
'rps':10,
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'音乐录影带，官方为搭配音乐而拍摄的短片',
'url':'//www.bilibili.com/video/music-coordinate-1.html'
},
{
'name':'音乐现场',
'route':'live',
'tid':29,
'ps':15,
'rps':10,
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'音乐实况表演视频',
'url':'//www.bilibili.com/video/music-oped-1.html'
},
{
'name':'音乐综合',
'route':'other',
'tid':130,
'ps':15,
'rps':10,
'viewHotTag':0,
'dpConfig':[
{
'name':'一日',
'value':1
},
{
'name':'三日',
'value':3
}
],
'desc':'收录无法定义到其他音乐子分区的音乐视频',
'url':'//www.bilibili.com/video/music-collection-1.html'
},
{
'name':'音频',
'customZone':'Audio',
'route':'audio',
'url':'//www.bilibili.com/audio/home?musicType=music'
}
]
},
{
'name':'舞蹈',
'route':'dance',
'tid':129,
'locid':64,
'url':'//www.bilibili.com/video/dance.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2513,
'leftId':2472,
'rightId':2473
},
'sub':[
{
'name':'宅舞',
'route':'otaku',
'tid':20,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':249
},
'desc':'与ACG相关的翻跳、原创舞蹈',
'url':'//www.bilibili.com/video/dance-1.html'
},
{
'name':'三次元舞蹈',
'route':'three_d',
'tid':154,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':251
},
'desc':'以三次元音乐作为BGM的舞蹈',
'url':'//www.bilibili.com/video/three-dimension-dance-1.html'
},
{
'name':'舞蹈教程',
'route':'demo',
'tid':156,
'ps':10,
'rps':6,
'ad':{
'active':0,
'dataLocId':253
},
'desc':'镜面慢速，动作分解，基础教程等具有教学意义的舞蹈视频',
'url':'//www.bilibili.com/video/dance-demo-1.html'
}
]
},
{
'name':'游戏',
'route':'game',
'tid':4,
'locid':70,
'url':'//www.bilibili.com/video/game.html',
'count':'',
'slider':{
'width':470,
'height':216
},
'viewTag':0,
'customComponent':{
'name':'Promote',
'id':4
},
'recommendCardType':'GameGroomBox',
'sub':[
{
'name':'单机游戏',
'route':'stand_alone',
'tid':17,
'ps':10,
'rps':7,
'rankshow':1,
'viewHotTag':0,
'ad':{
'active':0,
'dataLocId':255
},
'dpConfig':[
{
'name':'三日',
'value':3
},
{
'name':'一日',
'value':1
},
{
'name':'一周',
'value':7
}
],
'desc':'以所有平台（PC、主机、移动端）的单机或联机游戏为主的视频内容，包括游戏预告、CG、实况解说及相关的评测、杂谈与视频剪辑等',
'url':'//www.bilibili.com/video/videogame-1.html'
},
{
'name':'电子竞技',
'route':'esports',
'tid':171,
'ps':10,
'rps':7,
'rankshow':1,
'viewHotTag':0,
'ad':{
'active':0,
'dataLocId':257
},
'desc':'具有高对抗性的电子竞技游戏项目，其相关的赛事、实况、攻略、解说、短剧等视频。',
'url':'//www.bilibili.com/video/esports-1.html'
},
{
'name':'手机游戏',
'route':'mobile',
'tid':172,
'ps':10,
'rps':7,
'rankshow':1,
'viewHotTag':0,
'desc':'以手机及平板设备为主要平台的游戏，其相关的实况、攻略、解说、短剧、演示等视频。',
'url':'//www.bilibili.com/video/mobilegame-1.html'
},
{
'name':'网络游戏',
'route':'online',
'tid':65,
'ps':10,
'rps':7,
'rankshow':1,
'viewHotTag':0,
'ad':{
'active':0,
'dataLocId':259
},
'dpConfig':[
{
'name':'三日',
'value':3
},
{
'name':'一日',
'value':1
},
{
'name':'一周',
'value':7
}
],
'desc':'由网络运营商运营的多人在线游戏，以及电子竞技的相关游戏内容。包括赛事、攻略、实况、解说等相关视频',
'url':'//www.bilibili.com/video/onlinegame-1.html'
},
{
'name':'桌游棋牌',
'route':'board',
'tid':173,
'ps':5,
'rps':3,
'rankshow':1,
'viewHotTag':0,
'desc':'桌游、棋牌、卡牌对战等及其相关电子版游戏的实况、攻略、解说、演示等视频。',
'url':'//www.bilibili.com/video/boardgame-1.html'
},
{
'name':'GMV',
'route':'gmv',
'tid':121,
'ps':5,
'rps':3,
'rankshow':1,
'viewHotTag':0,
'dpConfig':[
{
'name':'三日',
'value':3
},
{
'name':'一日',
'value':1
},
{
'name':'一周',
'value':7
}
],
'desc':'由游戏素材制作的MV视频。以游戏内容或CG为主制作的，具有一定创作程度的MV类型的视频',
'url':'//www.bilibili.com/video/gmv-1.html'
},
{
'name':'音游',
'route':'music',
'tid':136,
'ps':5,
'rps':3,
'rankshow':1,
'viewHotTag':0,
'dpConfig':[
{
'name':'三日',
'value':3
},
{
'name':'一日',
'value':1
},
{
'name':'一周',
'value':7
}
],
'desc':'各个平台上，通过配合音乐与节奏而进行的音乐类游戏视频',
'url':'//www.bilibili.com/video/music-game-1.html'
},
{
'name':'Mugen',
'route':'mugen',
'tid':19,
'ps':5,
'rps':3,
'rankshow':1,
'viewHotTag':0,
'dpConfig':[
{
'name':'三日',
'value':3
},
{
'name':'一日',
'value':1
},
{
'name':'一周',
'value':7
}
],
'desc':'以Mugen引擎为平台制作、或与Mugen相关的游戏视频',
'url':'//www.bilibili.com/video/game-mugen-1.html'
},
{
'name':'游戏赛事',
'url':'//www.bilibili.com/v/game/match/',
'newIcon':0
}
]
},
{
'name':'科技',
'route':'technology',
'tid':36,
'locid':76,
'url':'//www.bilibili.com/video/technology.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2058,
'leftId':2047,
'rightId':2048
},
'sub':[
{
'name':'趣味科普人文',
'route':'fun',
'tid':124,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':261
},
'desc':'含有科普或人文性质的视频',
'url':'//www.bilibili.com/video/tech-fun-1.html'
},
{
'name':'野生技术协会',
'route':'wild',
'tid':122,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':263
},
'desc':'展示一定改装/创作能力的视频',
'url':'//www.bilibili.com/video/tech-wild-1.html'
},
{
'name':'演讲·公开课',
'route':'speech_course',
'tid':39,
'ps':15,
'rps':10,
'desc':'演讲、教育课程相关的视频',
'url':'//www.bilibili.com/video/speech-course-1.html'
},
{
'name':'星海',
'route':'military',
'tid':96,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':265
},
'desc':'军事相关视频',
'url':'//www.bilibili.com/video/tech-future-military-1.html'
},
{
'name':'机械',
'route':'mechanical',
'tid':98,
'ps':15,
'rps':10,
'desc':'机械设备展示或制作视频',
'url':'//www.bilibili.com/video/tech-future-other-1.html'
},
{
'name':'汽车',
'route':'automobile',
'tid':176,
'ps':15,
'rps':10,
'desc':'汽车、摩托车、公交车以及竞赛用车等轮式交通工具相',
'url':'//www.bilibili.com/video/tech-future-automobile-1.html'
}
]
},
{
'name':'数码',
'route':'digital',
'tid':188,
'locid':2977,
'url':'#',
'count':'',
'slider':{
'width':470,
'height':216
},
'viewTag':0,
'customComponent':{
'name':'Energy',
'titleId':2980,
'leftId':2978,
'rightId':2979
},
'recommendCardType':'GameGroomBox',
'sub':[
{
'name':'手机平板',
'route':'mobile',
'tid':95,
'ps':15,
'rps':10,
'viewHotTag':0,
'desc':'手机平板设备相关视频',
'url':'#'
},
{
'name':'电脑装机',
'route':'pc',
'tid':189,
'ps':15,
'rps':10,
'viewHotTag':0,
'desc':'电脑装机及配件等相关视频',
'url':'#'
},
{
'name':'摄影摄像',
'route':'photography',
'tid':190,
'ps':15,
'rps':10,
'viewHotTag':0,
'desc':'摄影摄像器材等相关视频',
'url':'#'
},
{
'name':'影音智能',
'route':'intelligence_av',
'tid':191,
'ps':15,
'rps':10,
'viewHotTag':0,
'desc':'影音设备、智能产品等相关视频',
'url':'#'
}
]
},
{
'name':'生活',
'route':'life',
'tid':160,
'locid':88,
'url':'//www.bilibili.com/video/life.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2062,
'leftId':1674,
'rightId':1670
},
'sub':[
{
'name':'搞笑',
'route':'funny',
'tid':138,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':273
},
'desc':'搞笑的、轻松有趣的、具有独特笑点或娱乐精神的视频',
'url':'//www.bilibili.com/video/ent_funny_1.html'
},
{
'name':'日常',
'route':'daily',
'tid':21,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':275
},
'desc':'漫展、cosplay、体育运动及其他一般日常向视频',
'url':'//www.bilibili.com/video/ent-life-1.html'
},
{
'name':'美食圈',
'route':'food',
'tid':76,
'ps':15,
'rps':10,
'desc':'美食鉴赏&料理制作教程',
'url':'//www.bilibili.com/video/ent-food-1.html'
},
{
'name':'动物圈',
'route':'animal',
'tid':75,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':277
},
'desc':'这里有各种萌萌哒动物哦~',
'url':'//www.bilibili.com/video/ent-animal-1.html'
},
{
'name':'手工',
'route':'handmake',
'tid':161,
'ps':15,
'rps':10,
'desc':'简易手工艺品的diy制作视频，例如；折纸、手账、橡皮章等',
'url':'//www.bilibili.com/video/ent-handmake-1.html'
},
{
'name':'绘画',
'route':'painting',
'tid':162,
'ps':15,
'rps':10,
'desc':'绘画爱好者们关于绘画技巧、绘图过程的分享交流场所',
'url':'//www.bilibili.com/video/ent-painting-1.html'
},
{
'name':'运动',
'route':'sports',
'tid':163,
'ps':15,
'rps':10,
'desc':'一般向运动项目以及惊险刺激的户外极限运动',
'url':'//www.bilibili.com/video/ent-sports-1.html'
},
{
'name':'其他',
'route':'other',
'tid':174,
'ps':15,
'rps':10,
'desc':'对于分区归属不明的视频进行归纳整合的特定分区。',
'url':'//www.bilibili.com/video/others-1.html'
}
]
},
{
'name':'鬼畜',
'route':'kichiku',
'tid':119,
'locid':100,
'url':'//www.bilibili.com/video/kichiku.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2509,
'leftId':2482,
'rightId':2483
},
'sub':[
{
'name':'鬼畜调教',
'route':'guide',
'tid':22,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':285
},
'desc':'使用素材在音频、画面上做一定处理，达到与BGM一定的同步感',
'url':'//www.bilibili.com/video/ent-Kichiku-1.html'
},
{
'name':'音MAD',
'route':'mad',
'tid':26,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':287
},
'desc':'使用素材音频进行一定的二次创作来达到还原原曲的非商业性质稿件',
'url':'//www.bilibili.com/video/douga-kichiku-1.html'
},
{
'name':'人力VOCALOID',
'route':'manual_vocaloid',
'tid':126,
'ps':15,
'rps':10,
'desc':'将人物或者角色的无伴奏素材进行人工调音，使其就像VOCALOID一样歌唱的技术',
'url':'//www.bilibili.com/video/kichiku-manual_vocaloid-1.html'
},
{
'name':'教程演示',
'route':'course',
'tid':127,
'ps':10,
'rps':6,
'rightComponent':{
'name':'CmImgList',
'id':148
},
'ad':{
'active':0,
'dataLocId':289
},
'hideDropdown':1,
'desc':'鬼畜相关的教程演示',
'url':'//www.bilibili.com/video/kichiku-course-1.html'
}
]
},
{
'name':'时尚',
'route':'fashion',
'tid':155,
'locid':94,
'url':'//www.bilibili.com/video/fashion.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2515,
'leftId':2492,
'rightId':2493
},
'sub':[
{
'name':'美妆',
'route':'makeup',
'tid':157,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':279
},
'desc':'涵盖妆容、发型、美甲等教程，彩妆、护肤相关产品测评、分享等',
'url':'//www.bilibili.com/video/fashion-makeup-fitness-1.html'
},
{
'name':'服饰',
'route':'clothing',
'tid':158,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':281
},
'desc':'服饰风格、搭配技巧相关的展示和教程视频',
'url':'//www.bilibili.com/video/fashion-clothing-1.html'
},
{
'name':'健身',
'route':'aerobics',
'tid':164,
'ps':15,
'rps':10,
'desc':'器械、有氧、拉伸运动等，以达到强身健体、减肥瘦身、形体塑造目的',
'url':'//www.bilibili.com/video/fashion-body-1.html'
},
{
'name':'T台',
'route':'catwalk',
'tid':159,
'ps':15,
'rps':10,
'desc':'发布会走秀现场及模特相关时尚片、采访、后台花絮',
'url':'#'
},
{
'name':'风尚标',
'route':'trends',
'tid':192,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':283
},
'desc':'时尚明星专访、街拍、时尚购物相关知识科普',
'url':'#'
}
]
},
{
'name':'广告',
'route':'ad',
'tid':165,
'locid':1466,
'url':'//www.bilibili.com/video/ad-ad-1.html',
'count':'',
'sub':[
{
'name':'广告',
'route':'ad',
'tid':166,
'desc':''
}
],
'slider':{
'width':1160,
'height':332
}
},
{
'name':'娱乐',
'route':'ent',
'tid':5,
'locid':82,
'url':'//www.bilibili.com/video/ent.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2067,
'leftId':2065,
'rightId':2066
},
'sub':[
{
'name':'综艺',
'route':'variety',
'tid':71,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':267
},
'desc':'国内外有趣的综艺和综艺相关精彩剪辑',
'url':'//www.bilibili.com/video/ent-variety-1.html'
},
{
'name':'明星',
'route':'star',
'tid':137,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':269
},
'desc':'娱乐圈动态、明星资讯相关',
'url':'//www.bilibili.com/video/ent-circle-1.html'
},
{
'name':'Korea相关',
'route':'korea',
'tid':131,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':271
},
'desc':'Korea相关音乐、舞蹈、综艺等视频',
'url':'//www.bilibili.com/video/ent-korea-1.html'
}
]
},
{
'name':'影视',
'route':'cinephile',
'tid':181,
'locid':2211,
'url':'//www.bilibili.com/video/cinephile.html',
'count':'',
'slider':{
'width':620,
'height':220
},
'viewTag':1,
'customComponent':{
'name':'Energy',
'titleId':2309,
'leftId':2307,
'rightId':2308
},
'sub':[
{
'name':'影视杂谈',
'route':'cinecism',
'tid':182,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':2212
},
'desc':'影视评论、解说、吐槽、科普等',
'url':'//www.bilibili.com/video/cinephile-cinecism.html'
},
{
'name':'影视剪辑',
'route':'montage',
'tid':183,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':2213
},
'desc':'对影视素材进行剪辑再创作的视频',
'url':'//www.bilibili.com/video/cinephile-montage.html'
},
{
'name':'短片',
'route':'shortfilm',
'tid':85,
'ps':15,
'rps':10,
'desc':'追求自我表达且具有特色的短片',
'url':'//www.bilibili.com/video/cinephile-shortfilm.html'
},
{
'name':'预告·资讯',
'route':'trailer_info',
'tid':184,
'ps':15,
'rps':10,
'ad':{
'active':0,
'dataLocId':2214
},
'desc':'影视类相关资讯，预告，花絮等视频',
'url':'//www.bilibili.com/video/cinephile-trailer-info.html'
},
{
'name':'特摄',
'route':'tokusatsu',
'tid':86,
'ps':15,
'rps':10,
'desc':'特摄相关衍生视频',
'url':'//www.bilibili.com/video/cinephile-tokusatsu.html'
}
]
},
{
'name':'纪录片',
'route':'documentary',
'tid':177,
'url':'//www.bilibili.com/documentary/',
'count':'',
'takeOvered':0,
'hasParent':0,
'sub':[
{
'name':'人文·历史',
'tid':37,
'route':'history',
'dise':'',
'url':'//www.bilibili.com/video/doco-history.html'
},
{
'name':'科学·探索·自然',
'tid':178,
'route':'science',
'dise':'',
'url':'//www.bilibili.com/video/doco-science.html'
},
{
'name':'军事',
'tid':179,
'route':'military',
'dise':'',
'url':'//www.bilibili.com/video/doco-military.html'
},
{
'name':'社会·美食·旅行',
'tid':180,
'route':'travel',
'dise':'',
'url':'//www.bilibili.com/video/doco-travel.html'
},
{
'name':'纪录片索引',
'url':'//www.bilibili.com/documentary/index/'
}
]
},
{
'name':'电影',
'route':'movie',
'tid':23,
'url':'//www.bilibili.com/movie/',
'count':'',
'takeOvered':0,
'hasParent':0,
'sub':[
{
'name':'华语电影',
'tid':147,
'route':'chinese',
'desc':'',
'url':'//www.bilibili.com/video/movie_chinese_1.html'
},
{
'name':'欧美电影',
'tid':145,
'route':'west',
'desc':'',
'url':'//www.bilibili.com/video/movie_west_1.html'
},
{
'name':'日本电影',
'tid':146,
'route':'japan',
'desc':'',
'url':'//www.bilibili.com/video/movie_japan_1.html'
},
{
'name':'其他国家',
'tid':83,
'route':'movie',
'desc':'',
'url':'//www.bilibili.com/video/movie-movie-1.html'
},
{
'name':'电影索引',
'url':'//www.bilibili.com/movie/index/'
}
]
},
{
'name':'电视剧',
'route':'tv',
'tid':11,
'url':'//www.bilibili.com/tv/',
'count':'',
'takeOvered':0,
'hasParent':0,
'sub':[
{
'name':'国产剧',
'tid':185,
'route':'mainland',
'desc':'',
'url':'//www.bilibili.com/video/tv-mainland.html'
},
{
'name':'海外剧',
'tid':187,
'route':'overseas',
'desc':'',
'url':'//www.bilibili.com/video/tv-overseas.html'
},
{
'name':'电视剧索引',
'url':'//www.bilibili.com/tv/index/'
}
]
}
]

for i in z:
    if i['sub']:
        for n in i['sub']:
            if 'tid' in n :
                print('{}-{}-{}'.format(i['name'],n['name'],n['tid']))